
#==========================
# 工作流的名字（随便写）
name: openwrt_p2w_master
#==========================
env:
  GITEE_TOKEN: ${{ secrets.gitee }}
on:
  push:
    paths:
      #==========================
      - "p2w_master.config"
      # 改成和上方CONFIG_FILE 一样
      #==========================
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 抓取当前仓库
        uses: actions/checkout@master

      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        path: art
        with:
          name: "OpenWrt_firmware openwrt固件"

      - name: upload to gitee
        run: |
          git config --local user.email "lietxia@gmail.com"
          git config --local user.name "lietxia"
          git clone https://lietxia_admin:${GITEE_TOKEN}@gitee.com/lietxia_admin/openwrt_bin.git rom
          mv -rf art rom/art/
          cd rom
          git add . || echo "1"
          git commit -m "github_actions" -a;
          git push

      - name: SSH connection to Actions
        uses: P3TERX/debugger-action@master
